version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: walpulse-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: appdb
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    ports:
      - "5432:5432"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: walpulse-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L622nShTUiBenAAnKdADg'
    ports:
      - "9092:9092"

  walpulse:
    build: .
    container_name: walpulse-engine
    depends_on:
      - postgres
      - kafka
    environment:
      WALPULSE_PG_HOST: postgres
      WALPULSE_PG_PORT: 5432
      WALPULSE_PG_DB: appdb
      WALPULSE_PG_USER: postgres
      WALPULSE_PG_PASSWORD: postgrespassword
      WALPULSE_SINK_TYPE: kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8080:8080"
